# Generated by Django 3.0.1 on 2020-01-27 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinstagramUserSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('personal_url', models.CharField(max_length=1000)),
                ('bio', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('settings_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.CinstagramUser')),
            ],
        ),
    ]
