# Generated by Django 3.0.1 on 2020-01-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_settings', '0002_auto_20200127_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinstagramusersettings',
            name='private_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cinstagramusersettings',
            name='turn_off_comments',
            field=models.BooleanField(default=False),
        ),
    ]
