# Generated by Django 3.0.1 on 2020-01-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_settings', '0004_auto_20200129_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinstagramusersettings',
            old_name='reminder',
            new_name='reminder_emails',
        ),
        migrations.RenameField(
            model_name='cinstagramusersettings',
            old_name='sms_notifications',
            new_name='sms_messages',
        ),
    ]
