# Generated by Django 3.0.1 on 2020-02-04 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_settings', '0006_auto_20200129_1133'),
        ('media_upload', '0003_userphotocomment_comment_owner_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphotolike',
            name='like_owner_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_settings.CinstagramUserSettings'),
        ),
    ]
