# Generated by Django 3.0.1 on 2020-02-06 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media_upload', '0004_userphotolike_like_owner_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphotobookmark',
            name='bookmark_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
