"""empty message

Revision ID: a5ed1324bca7
Revises: a20847e585c1
Create Date: 2019-10-05 16:30:13.627538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ed1324bca7'
down_revision = 'a20847e585c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programmer', sa.Column('verification_key', sa.String(length=20), nullable=True))
    op.drop_column('programmer', 'key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programmer', sa.Column('key', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('programmer', 'verification_key')
    # ### end Alembic commands ###
