"""empty message

Revision ID: a5f675b922ad
Revises: 
Create Date: 2019-10-05 14:36:26.007950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f675b922ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('programmer_password_key', 'programmer', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('programmer_password_key', 'programmer', ['password'])
    # ### end Alembic commands ###
