"""empty message

Revision ID: d2901ee24410
Revises: a5ed1324bca7
Create Date: 2019-10-05 16:32:49.792125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2901ee24410'
down_revision = 'a5ed1324bca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programmer', sa.Column('key', sa.String(length=20), nullable=True))
    op.drop_column('programmer', 'verification_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programmer', sa.Column('verification_key', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('programmer', 'key')
    # ### end Alembic commands ###
