# Generated by Django 3.0.1 on 2020-02-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_settings', '0006_auto_20200129_1133'),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowing',
            name='followed_user_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_user_settings', to='profile_settings.CinstagramUserSettings'),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='follower_user_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_user_settings', to='profile_settings.CinstagramUserSettings'),
        ),
    ]
