"""empty message

Revision ID: d61cce15addc
Revises: 7b7605a9698c
Create Date: 2019-12-24 21:12:09.248096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d61cce15addc"
down_revision = "7b7605a9698c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("photo", sa.LargeBinary(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=True),
        sa.Column("caption", sa.String(length=2200), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["cinstagram_user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_photo_bookmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bookmarked_photo_id", sa.Integer(), nullable=True),
        sa.Column("bookmarker_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["bookmarked_photo_id"], ["user_photos.id"]),
        sa.ForeignKeyConstraint(["bookmarker_id"], ["cinstagram_user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_photo_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("commented_photo_id", sa.Integer(), nullable=True),
        sa.Column("comment_owner_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(length=2200), nullable=True),
        sa.Column("comment_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["comment_owner_id"], ["cinstagram_user.id"]),
        sa.ForeignKeyConstraint(["commented_photo_id"], ["user_photos.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_photo_likes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("liked_photo_id", sa.Integer(), nullable=True),
        sa.Column("like_owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["like_owner_id"], ["cinstagram_user.id"]),
        sa.ForeignKeyConstraint(["liked_photo_id"], ["user_photos.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_photo_likes")
    op.drop_table("user_photo_comments")
    op.drop_table("user_photo_bookmarks")
    op.drop_table("user_photos")
    # ### end Alembic commands ###
